export const objectTypes = [
  "Autre",
  "Téléphone",
  "Ordinateur portable",
  "Tablette",
  "Casque audio",
  "Clé USB",
  "Chargeur",
  "document",
  "passport",
  "carte d'identité",
  "Portefeuille",
  "Porte-monnaie",
  "Lunettes de vue",
  "Bijoux",
  "Sac à main",
  "Sac à dos",
  "Valise",
  "Écharpe",
  "Chapeau",
  "Casquette",
  "Chaussures",
  "vêtement",
  "Livre",
  "Coussin de voyage",
  "Poussette",
  "Siège auto pour enfant",
  "Jouet",
];
