export const objectTypes = [
  "Téléphone",
  "Ordinateur portable",
  "Tablette",
  "Casque audio",
  "Écouteurs",
  "Clé USB",
  "Chargeur",
  "Passeport",
  "Carte d'identité",
  "Permis de conduire",
  "Carte bancaire",
  "Portefeuille",
  "Porte-monnaie",
  "Argent liquide",
  "Lunettes de vue",
  "Lunettes de soleil",
  "Montre",
  "Bijoux",
  "Sac à main",
  "Sac à dos",
  "Valise",
  "Trousse",
  "Veste",
  "Manteau",
  "Écharpe",
  "Gants",
  "Chapeau",
  "Casquette",
  "Ceinture",
  "Chaussures",
  "T-shirt",
  "Jean",
  "Robe",
  "Livre",
  "Kindle",
  "Nintendo Switch",
  "Coussin de voyage",
  "Canne",
  "Poussette",
  "Siège auto pour enfant",
  "Jouet",
  "Parapluie",
  "Bouteille d'eau",
  "AirTag",
  "Autre",
];
